spring:
  data:
    mongodb:
      uri: mongodb+srv://lokeshbirle09_db_user:MongoDB@cluster0.8nnx9ar.mongodb.net/resumebuilder?retryWrites=true&w=majority&appName=Cluster0

server:
  port: 8080

jwt:
  secret: niralosResumeBuilderSuperSecretKeyForJwtSigning2024ChangeThisInProd
  expiration: 86400000